apiVersion: apps/v1
kind: Deployment
metadata:
  # задает имя (префикс имени) для создаваемых Pod-ов и имя деплоя
  name: frontend
  # задает метки для ReplicaSet объекта
  labels:
    name: frontend
spec:
  # количество запускаемых реплик
  replicas: 3
  
  # с помощью селектора происходит выборка pod-ов по меткам, которые указаны в шаблоне Pod-a
  # контроллер управляет pod-ами, которые попали в выборку
  selector:
    matchLabels:
      app: frontend
  
  # описание шаблона создаваемого Pod-а
  template:
    # задает метки для Pod-ов создаваемых этим шаблоном
    metadata:
      labels:
        app: frontend
        branch: kubernetes-controllers
        ver: v0.0.2
    # определяет список контейнеров, которые будут созданы
    spec:
      containers:
      - name: frontend
        image: slkrylov/otus:v0.0.2
        imagePullPolicy: Always
        
        readinessProbe:
          # задает количество секунд через, которое будет выполнена проверка после запуска контейнера 
          initialDelaySeconds: 10
          # задает, что для проверки будет выполнен HTTP-запрос
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
                