apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    homework: no1
    role: static-web
    app: web
spec:
  containers:
  - name: web-app-no1
    image: slkrylov/otus:kubernetes-intro
    volumeMounts:
      - mountPath: /app
        name: app
  initContainers:
  - name: init-web-app-no1
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - mountPath: /app
        name: app
  volumes:
  - name: app
    emptyDir: {}
